### PR TITLE
Do not implicit relative import

### PR DESCRIPTION
**Pull request by narusemotoki**
Weekly cleanup

Implicit relative importing does not work with Python 3.
This is the reason why gengo-python cannot install via pip for Python 3.

I combined my another pull request, because it is inconvenient that test file is in main package for this change. But I removed coverage, because it does not work with Python 3.2.
https://github.com/gengo/gengo-python/pull/81

Now it works with Python 3.
```
% python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gengo
>>> gengo.Gengo('public', 'private')                                                                                                                                                                                                                                                       
<gengo.gengo.Gengo object at 0x7fa25a608fd0>
```

And Python 2.
```
% python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gengo
>>> gengo.Gengo('public', 'private')
<gengo.gengo.Gengo object at 0x7feb24d7e9d0>
```

Before changes:
```
% python
Python 3.5.1+ (default, Mar 30 2016, 22:46:26) 
[GCC 5.3.1 20160330] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gengo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/motoki/workspace/gengo-python/gengo/__init__.py", line 34, in <module>
    from gengo import Gengo, GengoError, GengoAuthError
ImportError: cannot import name 'Gengo'
```

### CODE REVIEW

**Comment by hayate** [comment]
great job @narusemotoki :bowing_man: 
*L***GT***M*

**Comment by trinchan** [comment]
LGTM
